clickhouse:
  online:
    host: "192.168.115.129"
    port: 9000          # native 协议端口
    http_port: 8123     # 修改为 8123
    username: "default"
    password: ""
    database: "online"
  offline:
    host: "192.168.115.129"
    port: 9000
    http_port: 8123
    username: "default"
    password: ""
    database: "offline"