# Kafka 配置
kafka:
  bootstrap_servers: "192.168.115.129:9092"   # 改为 9092
  topics:
    online: "hdfs-logs-online"
    offline: "hdfs-logs-offline"
  producer:
    acks: 1
    retries: 3
    batch_size: 65536
    linger_ms: 10
    compression_type: "gzip"